default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: freemarket_sample_65b_development

test:
  <<: *default
  database: freemarket_sample_65b_test

production:
  <<: *default
  database: freemarket_sample_65b_production
  username: freemarket_sample_65b
  password: <%= ENV['FREEMARKET_SAMPLE_65B_DATABASE_PASSWORD'] %>